services:
  - docker:dind

build-job:
  stage: build
  tags: 
    - clipperz-build
  variables:
    IMAGE_NAME: password-manager
    IMAGE_FULL_NAME: clipperz/${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    #- docker build -t ${IMAGE_FULL_NAME} .
    #- docker push ${CI_REGISTRY}/${IMAGE_FULL_NAME}
    - apk update && apk add git
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.imolab.it/clipperz/clipperz-docker-compose.git