build-job:
  stage: build
  tags: 
    - clipperz-build
  variables:
   IMAGE_NAME: password-manager
  before_script:
    - docker login -u '$CI_REGISTRY_USER' -p '$CI_REGISTRY_PASSWORD' registry.imolab.it
  script:
    - docker build -t clipperz/'$IMAGE_NAME':'$CI_COMMIT_SHORT_SHA' .
    - docker push registry.imolab.it/clipperz/'$IMAGE_NAME:$CI_COMMIT_SHORT_SHA'