build-job:
  stage: build
  variables:
   IMAGE_NAME: clipperz-app
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push registry.imolab.it/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA