services:
  - docker:dind

build-job:
  stage: build
  tags: 
    - clipperz-build
  variables:
   IMAGE_NAME: password-manager
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin registry.imolab.it
  script:
    - docker build -t clipperz/${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA} .
    - docker push registry.imolab.it/clipperz/${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}